networks:
  minilab:
    name: minilab
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  docker-proxy:
    name: docker-proxy
    driver: bridge
    internal: true

include:
  - path: ./docker-compose.network.yml
  - path: ./docker-compose.utils.yml
  - path: ./docker-compose.game-servers.yml
  - path: ./docker-compose.dev-tools.yml
  - path: ./docker-compose.apps.yml