services:
  valheim:
    image: tsxcloud/valheim-arm:arm64
    container_name: valheim
    cap_add:
      - sys_nice
    environment:
      - SERVER_NAME=${VALHEIM_SERVER_NAME}
      - WORLD_NAME=${VALHEIM_WORLD_NAME}
      - SERVER_PASSWORD=${VALHEIM_PASSWORD}
      - SERVER_PUBLIC=0
      - UPDATE=enabled
      - SAVE_INTERVAL=1800
      - TZ=Europe/Paris
    volumes:
      - /mnt/ssd/valheim:/root/.config/unity3d/IronGate/Valheim
      - /mnt/ssd/valheim/backups:/data/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/2456"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 240s
    network_mode: "service:wireguard"
    depends_on:
      wireguard:
        condition: service_healthy
    labels:
      - "minilab.service=valheim"

  cobblemon:
    image: itzg/minecraft-server:java21
    container_name: cobblemon
    tty: true
    stdin_open: true
    environment:
      - UID=1000
      - GID=1000
      - EULA=TRUE
      - TZ=Europe/Paris
      - TYPE=FABRIC
      - MOD_PLATFORM=MODRINTH
      - MODRINTH_MODPACK=cobblemon-fabric
      - MODRINTH_LOADER=fabric
      - INIT_MEMORY=2G
      - MAX_MEMORY=5G
      - DIFFICULTY=normal
      - MOTD=${COBBLEMON_MOTD}
      - MAX_PLAYERS=3
      - PVP=FALSE
      - SERVER_NAME=${COBBLEMON_SERVER_NAME}
      - SPAWN_MONSTERS=false
    volumes:
      - /mnt/ssd/cobblemon:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/25565"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 240s
    network_mode: "service:wireguard"
    depends_on:
      wireguard:
        condition: service_healthy
    labels:
      - "minilab.service=cobblemon"

  terraria:
    image: hexlo/terraria-server-docker:latest
    container_name: terraria
    tty: true
    stdin_open: true
    environment:
      - TZ=Europe/Paris
      - world=${TERRARIA_WORLD_NAME}.wld
      - autocreate=2
      - difficulty=0
      - maxplayers=8
      - password=${TERRARIA_PASSWORD}
      - motd=${TERRARIA_MOTD}
      - language=fr/FR
    volumes:
      - /mnt/ssd/terraria/worlds:/root/.local/share/Terraria/Worlds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/7777"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 120s
    network_mode: "service:wireguard"
    depends_on:
      wireguard:
        condition: service_healthy
    labels:
      - "minilab.service=terraria"