networks:
  minilab:
    external: true

services:
   mariadb:
     image: lscr.io/linuxserver/mariadb:latest
     container_name: mariadb
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/Paris
       - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
     volumes:
       - /mnt/ssd/mariadb/config:/config
     restart: unless-stopped
     networks:
       minilab:
         ipv4_address: 172.20.0.40